[build]
builder = "NIXPACKS"
buildCommand = "NODE_OPTIONS=--max-old-space-size=4096 yarn install && NODE_OPTIONS=--max-old-space-size=4096 yarn build"

[deploy]
preDeployCommand = "yarn medusa db:migrate && yarn medusa exec ./src/scripts/create-admin.ts && yarn seed"
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
